GRANT USAGE ON SCHEMA PUBLIC TO metabase_reader;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA PUBLIC TO metabase_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO metabase_reader;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO crawler;
