GRANT USAGE ON SCHEMA PUBLIC TO metabase_reader;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA PUBLIC TO metabase_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO metabase_reader;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO crawler;

CREATE ROLE librarian;
GRANT ALL PRIVILEGES ON TABLE rated_match TO librarian;
GRANT ALL PRIVILEGES ON TABLE team_encounter TO librarian;
